### ISSUE TITLE
ComfyUI-Yvann_Nodes v1 Checklist

### ISSUE THREAD

**Issue by yvann-ba** [yvann-ba/ComfyUI_Yvann-Nodes#3]
- [ ]  Add Outputs Masks based on weights
- [ ] Add others audio extraction in analysis_mode: others audio, specialized kick etc...
- [ ] Add a node to adapt the range of the node to animatediff multival
- [ ] make work mask output with controlnet and others stuff
- [ ] Round values of weights to 0.111
